"""Execute the tools selected by the supervisor plan.

One graph node owns tool execution so the graph can cleanly support:
- SQL only
- RAG only
- SQL + RAG
- reviewer-requested re-execution of one or both tools
"""

import logging

from src.agent.state import AgentState
from src.agent.nodes.schema_retriever import schema_retriever_node
from src.agent.nodes.sql_generator import sql_generator_node
from src.agent.nodes.sql_executor import sql_executor_node
from src.agent.nodes.rag_retriever_node import rag_retriever_node
from src.observability.langfuse_tracer import trace_span

logger = logging.getLogger(__name__)


def _planned_tools(state: AgentState) -> list[str]:
    plan = state.get("plan", {})
    return [str(step.get("tool", "")).lower() for step in plan.get("steps", [])]


def _tools_to_run(state: AgentState) -> list[str]:
    if state.get("review_decision") == "retry_tools":
        requested = [str(x).lower() for x in state.get("review_retry_tools", [])]
        planned = set(_planned_tools(state))
        return [tool for tool in requested if tool in {"sql", "rag"} and tool in planned]
    if state.get("execution_scope") == "retry":
        requested = [str(x).lower() for x in state.get("retry_tools", [])]
        planned = set(_planned_tools(state))
        return [tool for tool in requested if tool in {"sql", "rag"} and tool in planned]
    return _planned_tools(state)


def _clear_tool_output(state: AgentState, tool: str) -> AgentState:
    updated = dict(state)
    if tool == "sql":
        updated.update({
            "schema_context": "",
            "sql_columns": [],
            "sql_rows": [],
        })
        # On a reviewer-requested retry, retain the previous SQL/error so the
        # SQL worker can correct it using the review feedback. A new supervisor
        # plan starts clean.
        if state.get("execution_scope") != "retry":
            updated.update({"sql_query": "", "sql_error": None})
    elif tool == "rag":
        updated.update({
            "rag_context": "",
            "rag_sources": [],
            "rag_error": None,
        })
    return updated


def tool_executor_node(state: AgentState) -> AgentState:
    if state.get("blocked"):
        return state

    trace = state.get("trace")
    tools = _tools_to_run(state)
    if not tools:
        return {**state, "draft_response": "", "sql_error": "No valid tool was selected by the supervisor."}

    working = dict(state)
    if working.get("review_decision") == "retry_tools":
        working["execution_scope"] = "retry"
        working["retry_tools"] = tools
    for tool in tools:
        working = _clear_tool_output(working, tool)

    with trace_span(
        trace,
        "plan_execution",
        input={
            "route": working.get("route"),
            "tools": tools,
            "scope": working.get("execution_scope", "plan"),
            "revision": working.get("plan_revision", 1),
            "review_attempt": working.get("review_attempts", 0),
        },
    ) as span:
        try:
            # SQL needs live/static schema context before generation.
            if "sql" in tools:
                working = schema_retriever_node(working)
                working = sql_generator_node(working)
                working = sql_executor_node(working)

            # RAG uses the focused query generated by the supervisor plan.
            if "rag" in tools:
                working = rag_retriever_node(working)

            span.update(
                output={
                    "sql_rows": len(working.get("sql_rows", []) or []),
                    "sql_error": working.get("sql_error"),
                    "rag_chunks": len(working.get("rag_sources", []) or []),
                    "rag_error": working.get("rag_error"),
                },
                metadata={"tools": tools},
            )
        except Exception as exc:
            logger.exception("Plan execution failed: %s", exc)
            span.update(output={"error": str(exc)}, level="ERROR")
            # Keep the graph alive so the reviewer can decide whether the
            # failed tool should be retried.
            if "sql" in tools:
                working["sql_error"] = working.get("sql_error") or str(exc)
            if "rag" in tools:
                working["rag_error"] = working.get("rag_error") or str(exc)

    return {
        **working,
        "retry_tools": [],
    }
